invite_mode:
  Default: 1

enable_mobile:
  Default: 1

enable_pc:
  Default: 1

auth_mode_caption:
  IsConfig: 0
  Default: "Username Login"

self_invite_action:
  IsConfig: 0
  Default: "authUsername/register"

require_mailaddress:
  FormType: "radio"
  IsRequired: true
  Caption: "Mail address in register"
  Default: 1
  Choices:
    1: "Require mail address"
    0: "Do not require mail address"